---
name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compiler version
        run: cc --version
      - name: Build
        run: make
      - name: Test
        run: make test
