---
name: release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Build linux package
        run: ./package.sh linux
      - name: version
        run: echo "::set-output name=version::$(./rle-zoo --version | cut -d ' ' -f 2)"
        id: version
      - name: Create release
        uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: false
          tag_name: ${{ github.ref }}
          release_name: rle-zoo ${{ steps.version.outputs.version }}
          body_path: CHANGES.md
      - name: Upload linux package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./packages/rle-zoo-${{ steps.version.outputs.version }}.linux-x86_64.tar.gz
          asset_name: rle-zoo-${{ steps.version.outputs.version }}-linux-x86_64.tar.gz
          asset_content_type: application/gzip
